version: '3'

services:
  nginx-proxy:
    image: nginx
    container_name: nginx-proxy
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
#      - ./www:/var/www:ro
      - ./conf.d:/etc/nginx/conf.d:ro
#      - ./ssl:/etc/nginx/ssl:ro
#      - ./snippets:/etc/nginx/snippets:ro
#      - ./protect:/etc/nginx/protect:ro

